export const colorStyles = {
  red: {
    buttonText: "text-red-600",
    buttonBg: "bg-red-50",
    buttonBorder: "border-r-red-500",
    optionFocusBg: "data-[focus]:bg-red-50",
    optionFocusText: "data-[focus]:text-red-600",
    optionSelectedBg: "data-[selected]:bg-red-50",
    optionSelectedText: "data-[selected]:text-red-600",
  },
  orange: {
    buttonText: "text-orange-600",
    buttonBg: "bg-orange-50",
    buttonBorder: "border-r-orange-500",
    optionFocusBg: "data-[focus]:bg-orange-50",
    optionFocusText: "data-[focus]:text-orange-600",
    optionSelectedBg: "data-[selected]:bg-orange-50",
    optionSelectedText: "data-[selected]:text-orange-600",
  },
  amber: {
    buttonText: "text-amber-600",
    buttonBg: "bg-amber-50",
    buttonBorder: "border-r-amber-500",
    optionFocusBg: "data-[focus]:bg-amber-50",
    optionFocusText: "data-[focus]:text-amber-600",
    optionSelectedBg: "data-[selected]:bg-amber-50",
    optionSelectedText: "data-[selected]:text-amber-600",
  },
  yellow: {
    buttonText: "text-yellow-600",
    buttonBg: "bg-yellow-50",
    buttonBorder: "border-r-yellow-500",
    optionFocusBg: "data-[focus]:bg-yellow-50",
    optionFocusText: "data-[focus]:text-yellow-600",
    optionSelectedBg: "data-[selected]:bg-yellow-50",
    optionSelectedText: "data-[selected]:text-yellow-600",
  },
  lime: {
    buttonText: "text-lime-600",
    buttonBg: "bg-lime-50",
    buttonBorder: "border-r-lime-500",
    optionFocusBg: "data-[focus]:bg-lime-50",
    optionFocusText: "data-[focus]:text-lime-600",
    optionSelectedBg: "data-[selected]:bg-lime-50",
    optionSelectedText: "data-[selected]:text-lime-600",
  },
  green: {
    buttonText: "text-green-600",
    buttonBg: "bg-green-50",
    buttonBorder: "border-r-green-500",
    optionFocusBg: "data-[focus]:bg-green-50",
    optionFocusText: "data-[focus]:text-green-600",
    optionSelectedBg: "data-[selected]:bg-green-50",
    optionSelectedText: "data-[selected]:text-green-600",
  },
  emerald: {
    buttonText: "text-emerald-600",
    buttonBg: "bg-emerald-50",
    buttonBorder: "border-r-emerald-500",
    optionFocusBg: "data-[focus]:bg-emerald-50",
    optionFocusText: "data-[focus]:text-emerald-600",
    optionSelectedBg: "data-[selected]:bg-emerald-50",
    optionSelectedText: "data-[selected]:text-emerald-600",
  },
  teal: {
    buttonText: "text-teal-600",
    buttonBg: "bg-teal-50",
    buttonBorder: "border-r-teal-500",
    optionFocusBg: "data-[focus]:bg-teal-50",
    optionFocusText: "data-[focus]:text-teal-600",
    optionSelectedBg: "data-[selected]:bg-teal-50",
    optionSelectedText: "data-[selected]:text-teal-600",
  },
  cyan: {
    buttonText: "text-cyan-600",
    buttonBg: "bg-cyan-50",
    buttonBorder: "border-r-cyan-500",
    optionFocusBg: "data-[focus]:bg-cyan-50",
    optionFocusText: "data-[focus]:text-cyan-600",
    optionSelectedBg: "data-[selected]:bg-cyan-50",
    optionSelectedText: "data-[selected]:text-cyan-600",
  },
  sky: {
    buttonText: "text-sky-600",
    buttonBg: "bg-sky-50",
    buttonBorder: "border-r-sky-500",
    optionFocusBg: "data-[focus]:bg-sky-50",
    optionFocusText: "data-[focus]:text-sky-600",
    optionSelectedBg: "data-[selected]:bg-sky-50",
    optionSelectedText: "data-[selected]:text-sky-600",
  },
  blue: {
    buttonText: "text-blue-600",
    buttonBg: "bg-blue-50",
    buttonBorder: "border-r-blue-500",
    optionFocusBg: "data-[focus]:bg-blue-50",
    optionFocusText: "data-[focus]:text-blue-600",
    optionSelectedBg: "data-[selected]:bg-blue-50",
    optionSelectedText: "data-[selected]:text-blue-600",
  },
  indigo: {
    buttonText: "text-indigo-600",
    buttonBg: "bg-indigo-50",
    buttonBorder: "border-r-indigo-500",
    optionFocusBg: "data-[focus]:bg-indigo-50",
    optionFocusText: "data-[focus]:text-indigo-600",
    optionSelectedBg: "data-[selected]:bg-indigo-50",
    optionSelectedText: "data-[selected]:text-indigo-600",
  },
  violet: {
    buttonText: "text-violet-600",
    buttonBg: "bg-violet-50",
    buttonBorder: "border-r-violet-500",
    optionFocusBg: "data-[focus]:bg-violet-50",
    optionFocusText: "data-[focus]:text-violet-600",
    optionSelectedBg: "data-[selected]:bg-violet-50",
    optionSelectedText: "data-[selected]:text-violet-600",
  },
  purple: {
    buttonText: "text-purple-600",
    buttonBg: "bg-purple-50",
    buttonBorder: "border-r-purple-500",
    optionFocusBg: "data-[focus]:bg-purple-50",
    optionFocusText: "data-[focus]:text-purple-600",
    optionSelectedBg: "data-[selected]:bg-purple-50",
    optionSelectedText: "data-[selected]:text-purple-600",
  },
  fuchsia: {
    buttonText: "text-fuchsia-600",
    buttonBg: "bg-fuchsia-50",
    buttonBorder: "border-r-fuchsia-500",
    optionFocusBg: "data-[focus]:bg-fuchsia-50",
    optionFocusText: "data-[focus]:text-fuchsia-600",
    optionSelectedBg: "data-[selected]:bg-fuchsia-50",
    optionSelectedText: "data-[selected]:text-fuchsia-600",
  },
  pink: {
    buttonText: "text-pink-600",
    buttonBg: "bg-pink-50",
    buttonBorder: "border-r-pink-500",
    optionFocusBg: "data-[focus]:bg-pink-50",
    optionFocusText: "data-[focus]:text-pink-600",
    optionSelectedBg: "data-[selected]:bg-pink-50",
    optionSelectedText: "data-[selected]:text-pink-600",
  },
  rose: {
    buttonText: "text-rose-600",
    buttonBg: "bg-rose-50",
    buttonBorder: "border-r-rose-500",
    optionFocusBg: "data-[focus]:bg-rose-50",
    optionFocusText: "data-[focus]:text-rose-600",
    optionSelectedBg: "data-[selected]:bg-rose-50",
    optionSelectedText: "data-[selected]:text-rose-600",
  },
  gray: {
    buttonText: "text-gray-600",
    buttonBg: "bg-gray-50",
    buttonBorder: "border-r-gray-400",
    optionFocusBg: "data-[focus]:bg-gray-100",
    optionFocusText: "data-[focus]:text-gray-900",
    optionSelectedBg: "data-[selected]:bg-gray-100",
    optionSelectedText: "data-[selected]:text-gray-900",
  },
};